# Application Config for Spring Cloud Server
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/johnpemberton/mtest1/sccs-config
          username: johnpemberton
          password: ${SCCS_GITHUB_TOKEN}
          repos:
            app1:
              cloneOnStart: true
              uri: https://github.com/johnpemberton/mtest1/app1
              username: johnpemberton
              password: ${SCCS_GITHUB_TOKEN}